{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
{{- end }}