{{- if and .Values.mongodb.enabled .Values.mongodb.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mongodb-vpa
  namespace: {{ .Values.global.namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongodb
  updatePolicy:
    updateMode: {{ .Values.mongodb.vpa.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
    - containerName: chatapp-mongodb
      minAllowed:
        cpu: {{ .Values.mongodb.vpa.minCpu }}
        memory: {{ .Values.mongodb.vpa.minMemory }}
      maxAllowed:
        cpu: {{ .Values.mongodb.vpa.maxCpu }}
        memory: {{ .Values.mongodb.vpa.maxMemory }}
{{- end }}