{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      name: backend-pod
      labels: 
        app: {{ .Values.backend.name }}
    spec:
      containers:
      - name: chatapp-backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: NODE_ENV
          value: {{ .Values.backend.env.nodeEnv }}
        - name: MONGODB_URI
          value: {{ .Values.backend.env.mongodbUri | quote }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-jwt-secret
              key: jwt 
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: cloudinary-credentials
              key: cloud_name
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudinary-credentials
              key: api_key
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: cloudinary-credentials
              key: api_secret
        - name: PORT
          value: "{{ .Values.backend.port }}"
        
        # **# âš¡ ADDED RESOURCES FOR HPA**
        resources:
          requests:
            cpu: {{ .Values.backend.resources.requests.cpu }}
            memory: {{ .Values.backend.resources.requests.memory }}
          limits:
            cpu: {{ .Values.backend.resources.limits.cpu }}
            memory: {{ .Values.backend.resources.limits.memory }}
{{- end }}